# Form implementation generated from reading ui file '/home/alfphy/PycharmProjects/drawing_game/ui/containerForm.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ContainerForm(object):
    def setupUi(self, ContainerForm):
        ContainerForm.setObjectName("ContainerForm")
        ContainerForm.resize(720, 720)
        icon = QtGui.QIcon.fromTheme("applications-games")
        ContainerForm.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ContainerForm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_title = QtWidgets.QLabel(parent=ContainerForm)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_2.addWidget(self.label_title)
        self.button_menu = QtWidgets.QPushButton(parent=ContainerForm)
        self.button_menu.setObjectName("button_menu")
        self.horizontalLayout_2.addWidget(self.button_menu)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stack_pages = QtWidgets.QStackedWidget(parent=ContainerForm)
        self.stack_pages.setObjectName("stack_pages")
        self.horizontalLayout.addWidget(self.stack_pages)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(1, 1)

        self.retranslateUi(ContainerForm)
        QtCore.QMetaObject.connectSlotsByName(ContainerForm)

    def retranslateUi(self, ContainerForm):
        _translate = QtCore.QCoreApplication.translate
        ContainerForm.setWindowTitle(_translate("ContainerForm", "Speed Sketch"))
        self.label_title.setText(_translate("ContainerForm", "Speed Sketch"))
        self.button_menu.setText(_translate("ContainerForm", "Logout"))
