# Form implementation generated from reading ui file 'ui/containerForm.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import resources_rc.icons_rc
import resources_rc.background_rc


class Ui_ContainerForm(object):
    def setupUi(self, ContainerForm):
        ContainerForm.setObjectName("ContainerForm")
        ContainerForm.resize(1136, 970)
        icon = QtGui.QIcon.fromTheme("applications-games")
        ContainerForm.setWindowIcon(icon)
        ContainerForm.setStyleSheet("background-color:#161616; color:white;")
        self.verticalLayout = QtWidgets.QVBoxLayout(ContainerForm)
        self.verticalLayout.setContentsMargins(0, 0, 0, 90)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_bar = QtWidgets.QWidget(parent=ContainerForm)
        self.tab_bar.setMinimumSize(QtCore.QSize(0, 80))
        self.tab_bar.setMaximumSize(QtCore.QSize(16777215, 80))
        self.tab_bar.setAutoFillBackground(False)
        self.tab_bar.setStyleSheet("background-color:black\n"
";")
        self.tab_bar.setObjectName("tab_bar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_bar)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_title = QtWidgets.QLabel(parent=self.tab_bar)
        self.label_title.setStyleSheet("font: 600 oblique 21pt \"URW Gothic\";\n"
"border:none;\n"
"\n"
"margin-left:10px;\n"
"color:#2979FF;\n"
"")
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_4.addWidget(self.label_title)
        self.button_menu = QtWidgets.QPushButton(parent=self.tab_bar)
        self.button_menu.setEnabled(True)
        self.button_menu.setMinimumSize(QtCore.QSize(50, 50))
        self.button_menu.setMaximumSize(QtCore.QSize(50, 50))
        self.button_menu.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_menu.setStyleSheet("background:transparent\n"
"; \n"
"border-radius:20px;\n"
"")
        self.button_menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/general/arrow_back.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.button_menu.setIcon(icon)
        self.button_menu.setIconSize(QtCore.QSize(48, 48))
        self.button_menu.setCheckable(False)
        self.button_menu.setDefault(False)
        self.button_menu.setFlat(True)
        self.button_menu.setObjectName("button_menu")
        self.horizontalLayout_4.addWidget(self.button_menu)
        self.verticalLayout.addWidget(self.tab_bar)
        self.stack_pages = QtWidgets.QStackedWidget(parent=ContainerForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stack_pages.sizePolicy().hasHeightForWidth())
        self.stack_pages.setSizePolicy(sizePolicy)
        self.stack_pages.setMinimumSize(QtCore.QSize(800, 800))
        self.stack_pages.setObjectName("stack_pages")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stack_pages.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stack_pages.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stack_pages)

        self.retranslateUi(ContainerForm)
        QtCore.QMetaObject.connectSlotsByName(ContainerForm)

    def retranslateUi(self, ContainerForm):
        _translate = QtCore.QCoreApplication.translate
        ContainerForm.setWindowTitle(_translate("ContainerForm", "Speed Sketch"))
        self.label_title.setText(_translate("ContainerForm", "Speed Sketch"))
