# Form implementation generated from reading ui file 'ui\containerForm.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import resources_rc.background_rc
import resources_rc.icons_rc


class Ui_ContainerForm(object):
    def setupUi(self, ContainerForm):
        ContainerForm.setObjectName("ContainerForm")
        ContainerForm.resize(1563, 785)
        icon = QtGui.QIcon.fromTheme("applications-games")
        ContainerForm.setWindowIcon(icon)
        ContainerForm.setStyleSheet("background-color:#161616; color:white;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ContainerForm)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tab_bar = QtWidgets.QWidget(parent=ContainerForm)
        self.tab_bar.setAutoFillBackground(False)
        self.tab_bar.setStyleSheet("background-color:black\n"
";")
        self.tab_bar.setObjectName("tab_bar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_bar)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_title = QtWidgets.QLabel(parent=self.tab_bar)
        self.label_title.setStyleSheet("font: 600 oblique 30pt \"URW Gothic\";\n"
"border:none;\n"
"\n"
"margin-left:10px;\n"
"color:#2979FF;\n"
"")
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_4.addWidget(self.label_title)
        self.button_menu = QtWidgets.QPushButton(parent=self.tab_bar)
        self.button_menu.setMinimumSize(QtCore.QSize(50, 50))
        self.button_menu.setMaximumSize(QtCore.QSize(50, 50))
        self.button_menu.setStyleSheet("background-color:white; \n"
"border-radius:20px;\n"
"")
        self.button_menu.setText("")
        self.button_menu.setCheckable(False)
        self.button_menu.setDefault(False)
        self.button_menu.setFlat(True)
        self.button_menu.setObjectName("button_menu")
        self.horizontalLayout_4.addWidget(self.button_menu)
        self.horizontalLayout_2.addWidget(self.tab_bar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stack_pages = QtWidgets.QStackedWidget(parent=ContainerForm)
        self.stack_pages.setAutoFillBackground(False)
        self.stack_pages.setObjectName("stack_pages")
        self.horizontalLayout.addWidget(self.stack_pages)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(1, 1)

        self.retranslateUi(ContainerForm)
        QtCore.QMetaObject.connectSlotsByName(ContainerForm)

    def retranslateUi(self, ContainerForm):
        _translate = QtCore.QCoreApplication.translate
        ContainerForm.setWindowTitle(_translate("ContainerForm", "Speed Sketch"))
        self.label_title.setText(_translate("ContainerForm", "Speed Sketch"))
