# Form implementation generated from reading ui file 'ui/mainPage.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainMenu(object):
    def setupUi(self, mainMenu):
        mainMenu.setObjectName("mainMenu")
        mainMenu.resize(720, 345)
        icon = QtGui.QIcon.fromTheme("applications-games")
        mainMenu.setWindowIcon(icon)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(mainMenu)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(parent=mainMenu)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.button_easy = QtWidgets.QPushButton(parent=self.widget)
        self.button_easy.setMinimumSize(QtCore.QSize(300, 50))
        self.button_easy.setMaximumSize(QtCore.QSize(300, 16777215))
        self.button_easy.setObjectName("button_easy")
        self.verticalLayout_4.addWidget(self.button_easy)
        self.button_medium = QtWidgets.QPushButton(parent=self.widget)
        self.button_medium.setMinimumSize(QtCore.QSize(300, 50))
        self.button_medium.setMaximumSize(QtCore.QSize(300, 16777215))
        self.button_medium.setObjectName("button_medium")
        self.verticalLayout_4.addWidget(self.button_medium)
        self.button_hard = QtWidgets.QPushButton(parent=self.widget)
        self.button_hard.setMinimumSize(QtCore.QSize(300, 50))
        self.button_hard.setMaximumSize(QtCore.QSize(300, 16777215))
        self.button_hard.setObjectName("button_hard")
        self.verticalLayout_4.addWidget(self.button_hard)
        self.verticalLayout_2.addWidget(self.widget, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.analytics_container = QtWidgets.QHBoxLayout()
        self.analytics_container.setObjectName("analytics_container")
        self.verticalLayout.addLayout(self.analytics_container)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(mainMenu)
        QtCore.QMetaObject.connectSlotsByName(mainMenu)

    def retranslateUi(self, mainMenu):
        _translate = QtCore.QCoreApplication.translate
        mainMenu.setWindowTitle(_translate("mainMenu", "Speed Sketch"))
        self.button_easy.setText(_translate("mainMenu", "Easy"))
        self.button_medium.setText(_translate("mainMenu", "Medium"))
        self.button_hard.setText(_translate("mainMenu", "hard"))
