# Form implementation generated from reading ui file 'ui\mainPage.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import resources_rc.background_rc
import resources_rc.icons_rc


class Ui_mainMenu(object):
    def setupUi(self, mainMenu):
        mainMenu.setObjectName("mainMenu")
        mainMenu.resize(1646, 761)
        icon = QtGui.QIcon.fromTheme("applications-games")
        mainMenu.setWindowIcon(icon)
        mainMenu.setStyleSheet("background-color:#161616; color:white;")
        self.verticalLayout = QtWidgets.QVBoxLayout(mainMenu)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(parent=mainMenu)
        self.frame.setMinimumSize(QtCore.QSize(1400, 50))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setStyleSheet("background-color:transparent;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setSpacing(20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=self.frame)
        self.widget.setMinimumSize(QtCore.QSize(700, 150))
        self.widget.setMaximumSize(QtCore.QSize(1650, 150))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(9, 35, 1491, 106))
        self.label.setMinimumSize(QtCore.QSize(0, 100))
        self.label.setMaximumSize(QtCore.QSize(16777215, 150))
        self.label.setStyleSheet("border:none; background-color:transparent;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 201, 20))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setStyleSheet("color:#7da5e7; font-family: \"Arial\", \"Helvetica\", sans-serif;\n"
"\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(450, 550))
        self.frame_3.setStyleSheet("QFrame {\n"
"    background-color: #1c1b1b;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    background-color: #2B2B2A;\n"
"}")
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.easy_card_2 = QtWidgets.QWidget(parent=self.frame_3)
        self.easy_card_2.setMaximumSize(QtCore.QSize(350, 450))
        self.easy_card_2.setStyleSheet("background-color:transparent;")
        self.easy_card_2.setObjectName("easy_card_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.easy_card_2)
        self.verticalLayout_8.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_8.setSpacing(20)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_5 = QtWidgets.QWidget(parent=self.easy_card_2)
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 70))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_9 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_9.setMinimumSize(QtCore.QSize(48, 48))
        self.label_9.setMaximumSize(QtCore.QSize(48, 48))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/difficulty/child_care.svg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_13.addWidget(self.label_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_14 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_14.setMinimumSize(QtCore.QSize(100, 0))
        self.label_14.setMaximumSize(QtCore.QSize(120, 30))
        self.label_14.setStyleSheet("border:1px solid #31445F; border-radius: 0px\n"
"")
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_14.addWidget(self.label_14, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.horizontalLayout_10.addLayout(self.verticalLayout_14)
        self.verticalLayout_8.addWidget(self.widget_5)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_11 = QtWidgets.QLabel(parent=self.easy_card_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_11.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(parent=self.easy_card_2)
        self.label_12.setMaximumSize(QtCore.QSize(1000, 1000))
        self.label_12.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_11.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(parent=self.easy_card_2)
        self.label_13.setStyleSheet("color:#7da5e7;")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_11.addWidget(self.label_13)
        self.button_easy = QtWidgets.QPushButton(parent=self.easy_card_2)
        self.button_easy.setMinimumSize(QtCore.QSize(0, 60))
        self.button_easy.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_easy.setMouseTracking(False)
        self.button_easy.setStyleSheet("QPushButton{background-color:#0069EC;\n"
" font-weight: bold;\n"
" border-radius:20px;\n"
"    color: white;\n"
"    font-family: \"Arial\", \"Helvetica\", sans-serif;\n"
"\n"
"    font-weight: bold;\n"
"    font-style: italic;\n"
"    letter-spacing: -0.025em;\n"
"font-size:16px\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color:#0183FF;\n"
"}\n"
"")
        self.button_easy.setObjectName("button_easy")
        self.verticalLayout_11.addWidget(self.button_easy)
        self.verticalLayout_8.addLayout(self.verticalLayout_11)
        self.horizontalLayout_4.addWidget(self.easy_card_2)
        self.horizontalLayout_6.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame)
        self.frame_4.setMaximumSize(QtCore.QSize(450, 550))
        self.frame_4.setStyleSheet("QFrame {\n"
"    background-color: #1c1b1b;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    background-color: #2B2B2A;\n"
"}")
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.easy_card_3 = QtWidgets.QWidget(parent=self.frame_4)
        self.easy_card_3.setMinimumSize(QtCore.QSize(0, 0))
        self.easy_card_3.setMaximumSize(QtCore.QSize(350, 450))
        self.easy_card_3.setStyleSheet("background-color:transparent")
        self.easy_card_3.setObjectName("easy_card_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.easy_card_3)
        self.verticalLayout_9.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_9.setSpacing(20)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_6 = QtWidgets.QWidget(parent=self.easy_card_3)
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 70))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_10 = QtWidgets.QLabel(parent=self.widget_6)
        self.label_10.setMinimumSize(QtCore.QSize(48, 48))
        self.label_10.setMaximumSize(QtCore.QSize(48, 48))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/difficulty/bolt.svg"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_15.addWidget(self.label_10)
        self.horizontalLayout_11.addLayout(self.verticalLayout_15)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_15 = QtWidgets.QLabel(parent=self.widget_6)
        self.label_15.setMinimumSize(QtCore.QSize(100, 0))
        self.label_15.setMaximumSize(QtCore.QSize(120, 30))
        self.label_15.setStyleSheet("border:1px solid #31445F; border-radius: 0px;")
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_20.addWidget(self.label_15, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.horizontalLayout_11.addLayout(self.verticalLayout_20)
        self.verticalLayout_9.addWidget(self.widget_6)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_16 = QtWidgets.QLabel(parent=self.easy_card_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_12.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(parent=self.easy_card_3)
        self.label_17.setMaximumSize(QtCore.QSize(1000, 1000))
        self.label_17.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_12.addWidget(self.label_17)
        self.label_22 = QtWidgets.QLabel(parent=self.easy_card_3)
        self.label_22.setStyleSheet("color:#7da5e7;")
        self.label_22.setObjectName("label_22")
        self.verticalLayout_12.addWidget(self.label_22)
        self.button_medium = QtWidgets.QPushButton(parent=self.easy_card_3)
        self.button_medium.setMinimumSize(QtCore.QSize(0, 60))
        self.button_medium.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_medium.setStyleSheet("QPushButton{background-color:#E9C400;\n"
" font-weight: bold;\n"
" border-radius:20px;\n"
"    color: black;\n"
"    font-family: \"Arial\", \"Helvetica\", sans-serif;\n"
"\n"
"    font-weight: bold;\n"
"    font-style: italic;\n"
"    letter-spacing: -0.025em;\n"
"font-size:16px\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color:#FFD901;\n"
"}\n"
"")
        self.button_medium.setObjectName("button_medium")
        self.verticalLayout_12.addWidget(self.button_medium)
        self.verticalLayout_9.addLayout(self.verticalLayout_12)
        self.horizontalLayout_5.addWidget(self.easy_card_3)
        self.horizontalLayout_6.addWidget(self.frame_4)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(450, 550))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: #1c1b1b;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    background-color: #2B2B2A;\n"
"}")
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.easy_card_4 = QtWidgets.QWidget(parent=self.frame_2)
        self.easy_card_4.setMaximumSize(QtCore.QSize(350, 450))
        self.easy_card_4.setStyleSheet("    background-color: transparent;\n"
"")
        self.easy_card_4.setObjectName("easy_card_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.easy_card_4)
        self.verticalLayout_10.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_10.setSpacing(20)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_7 = QtWidgets.QWidget(parent=self.easy_card_4)
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 70))
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_21 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_21.setMinimumSize(QtCore.QSize(48, 48))
        self.label_21.setMaximumSize(QtCore.QSize(48, 48))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap(":/difficulty/fire_department.svg"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_16.addWidget(self.label_21)
        self.horizontalLayout_12.addLayout(self.verticalLayout_16)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_18 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_18.setMinimumSize(QtCore.QSize(100, 0))
        self.label_18.setMaximumSize(QtCore.QSize(120, 30))
        self.label_18.setStyleSheet("border:1px solid #31445F; border-radius: 0px;")
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_21.addWidget(self.label_18, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.horizontalLayout_12.addLayout(self.verticalLayout_21)
        self.verticalLayout_10.addWidget(self.widget_7)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_19 = QtWidgets.QLabel(parent=self.easy_card_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_17.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(parent=self.easy_card_4)
        self.label_20.setMaximumSize(QtCore.QSize(1000, 1000))
        self.label_20.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_17.addWidget(self.label_20)
        self.label_23 = QtWidgets.QLabel(parent=self.easy_card_4)
        self.label_23.setStyleSheet("color:#7da5e7;")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_17.addWidget(self.label_23)
        self.button_hard = QtWidgets.QPushButton(parent=self.easy_card_4)
        self.button_hard.setMinimumSize(QtCore.QSize(0, 60))
        self.button_hard.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_hard.setMouseTracking(False)
        self.button_hard.setStyleSheet("QPushButton{background-color:#0069EC;\n"
" font-weight: bold;\n"
" border-radius:20px;\n"
"    color: white;\n"
"    font-family: \"Arial\", \"Helvetica\", sans-serif;\n"
"\n"
"    font-weight: bold;\n"
"    font-style: italic;\n"
"    letter-spacing: -0.025em;\n"
"font-size:16px\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color:#0183FF;\n"
"}\n"
"")
        self.button_hard.setObjectName("button_hard")
        self.verticalLayout_17.addWidget(self.button_hard)
        self.verticalLayout_10.addLayout(self.verticalLayout_17)
        self.horizontalLayout_9.addWidget(self.easy_card_4)
        self.horizontalLayout_6.addWidget(self.frame_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_7 = QtWidgets.QFrame(parent=self.frame)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_7.setStyleSheet("background-color:#1c1b1b;\n"
"border-radius:20px;\n"
"border-left:2px solid #494F60;\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 161, 16))
        self.label_3.setStyleSheet("color:#7da5e7; font-family: \"Arial\", \"Helvetica\", sans-serif;\n"
"border:none;\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_6.setGeometry(QtCore.QRect(30, 50, 231, 50))
        self.label_6.setMinimumSize(QtCore.QSize(200, 50))
        self.label_6.setStyleSheet("border:none;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.frame_7, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_5.setStyleSheet("background-color:#1c1b1b;\n"
"border-radius:20px;\n"
"border-left:2px solid #494F60;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 161, 16))
        self.label_4.setStyleSheet("color:#7da5e7; font-family: \"Arial\", \"Helvetica\", sans-serif;\n"
"border:none;\n"
"\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_7.setGeometry(QtCore.QRect(30, 50, 231, 50))
        self.label_7.setMinimumSize(QtCore.QSize(200, 50))
        self.label_7.setStyleSheet("border:none;")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.frame_5, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_6 = QtWidgets.QFrame(parent=self.frame)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_6.setStyleSheet("background-color:#1c1b1b;\n"
"border-radius:20px;\n"
"border-left:2px solid #5A4E13;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_5.setGeometry(QtCore.QRect(30, 30, 161, 16))
        self.label_5.setStyleSheet("color:#E3BC03; font-family: \"Arial\", \"Helvetica\", sans-serif;\n"
"border:none;\n"
"\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_8.setGeometry(QtCore.QRect(30, 50, 231, 50))
        self.label_8.setMinimumSize(QtCore.QSize(200, 50))
        self.label_8.setStyleSheet("border:none;")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.frame_6, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 2)
        self.verticalLayout_4.addWidget(self.frame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout.setStretch(0, 6)

        self.retranslateUi(mainMenu)
        QtCore.QMetaObject.connectSlotsByName(mainMenu)

    def retranslateUi(self, mainMenu):
        _translate = QtCore.QCoreApplication.translate
        mainMenu.setWindowTitle(_translate("mainMenu", "Speed Sketch"))
        self.label.setText(_translate("mainMenu", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; font-size:72pt; font-weight:792; font-style:italic; color:#ffffff; text-transform:uppercase;\">DIFFICULTY</span></p></body></html>"))
        self.label_2.setText(_translate("mainMenu", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">SELECT YOUR VELOCITY.</span></p></body></html>"))
        self.label_14.setText(_translate("mainMenu", "<html><head/><body><p><span style=\" font-weight:600; color:#60a4fb;\">1.0+ XP</span></p></body></html>"))
        self.label_11.setText(_translate("mainMenu", "<html><head/><body><p><span style=\"font-family: sans-serif; font-size: 32pt; font-weight: 500; color: #ffffff; text-transform: uppercase; letter-spacing: 1px;\">EASY</span></p></body></html>"))
        self.label_12.setText(_translate("mainMenu", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; font-size:16pt; color:#a0a0a0;\">Relaxed timers and basic prompts. Perfect for warmups and casual sketches.</span></p></body></html>"))
        self.label_13.setText(_translate("mainMenu", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; font-size:14pt; color:#7c9cf8;\">✔</span><span style=\" font-family:\'sans-serif\'; font-size:14pt; color:#7da5e7;\"> 60 Seconds Initial time</span></p></body></html>"))
        self.button_easy.setText(_translate("mainMenu", "SELECT EASY"))
        self.label_15.setText(_translate("mainMenu", "<html><head/><body><p><span style=\" font-weight:600; color:#60a4fb;\">1.0+ XP</span></p></body></html>"))
        self.label_16.setText(_translate("mainMenu", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; font-size:32pt; font-weight:500; color:#ffffff; text-transform:uppercase;\">MEDIUM</span></p></body></html>"))
        self.label_17.setText(_translate("mainMenu", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; font-size:16pt; color:#a0a0a0;\">The sweet spot. Balanced timers with complex objects and dynamic themes.</span></p>"))
        self.label_22.setText(_translate("mainMenu", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; font-size:14pt; color:#7c9cf8;\">✔</span><span style=\" font-family:\'sans-serif\'; font-size:14pt; color:#7da5e7;\"> 60 Seconds Initial time</span></p></body></html>"))
        self.button_medium.setText(_translate("mainMenu", "SELECT MEDIUM"))
        self.label_18.setText(_translate("mainMenu", "<html><head/><body><p><span style=\" font-weight:600; color:#60a4fb;\">1.0+ XP</span></p></body></html>"))
        self.label_19.setText(_translate("mainMenu", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; font-size:32pt; font-weight:500; color:#ffffff; text-transform:uppercase;\">HARD</span></p></body></html>"))
        self.label_20.setText(_translate("mainMenu", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; font-size:16pt; color:#a0a0a0;\">Maximum intensity. Abstract prompts and ultra-fast timers. No mistakes allowed.\n"
"</span></p></body></html>"))
        self.label_23.setText(_translate("mainMenu", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; font-size:14pt; color:#7c9cf8;\">✔</span><span style=\" font-family:\'sans-serif\'; font-size:14pt; color:#7da5e7;\"> 60 Seconds Initial time</span></p></body></html>"))
        self.button_hard.setText(_translate("mainMenu", "SELECT HARD"))
        self.label_3.setText(_translate("mainMenu", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Personal Best</span></p></body></html>"))
        self.label_6.setText(_translate("mainMenu", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; font-size:25pt; font-weight:800; color:#ffffff;\">5s | 90%</span></p></body></html>"))
        self.label_4.setText(_translate("mainMenu", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Average Score</span></p></body></html>"))
        self.label_7.setText(_translate("mainMenu", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; font-size:25pt; font-weight:800; color:#ffffff;\">20s | 75%</span></p></body></html>"))
        self.label_5.setText(_translate("mainMenu", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Best Perfect Streak</span></p></body></html>"))
        self.label_8.setText(_translate("mainMenu", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; font-size:25pt; font-weight:800; color:#ffffff;\">12</span></p></body></html>"))
