# Form implementation generated from reading ui file 'ui\mainPage.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainMenu(object):
    def setupUi(self, mainMenu):
        mainMenu.setObjectName("mainMenu")
        mainMenu.resize(462, 486)
        icon = QtGui.QIcon.fromTheme("applications-games")
        mainMenu.setWindowIcon(icon)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(mainMenu)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=mainMenu)
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("background-color: rgb(107, 122, 245);")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget1 = QtWidgets.QWidget(parent=self.widget)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.button_easy = QtWidgets.QPushButton(parent=self.widget1)
        self.button_easy.setMinimumSize(QtCore.QSize(300, 50))
        self.button_easy.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.button_easy.setFont(font)
        self.button_easy.setAutoFillBackground(False)
        self.button_easy.setStyleSheet("background-color: rgb(255, 197, 66);\n"
"color: rgb(255, 255, 255);\n"
"padding: 0%;\n"
"")
        self.button_easy.setObjectName("button_easy")
        self.verticalLayout_4.addWidget(self.button_easy)
        self.button_medium = QtWidgets.QPushButton(parent=self.widget1)
        self.button_medium.setMinimumSize(QtCore.QSize(300, 50))
        self.button_medium.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.button_medium.setFont(font)
        self.button_medium.setAutoFillBackground(False)
        self.button_medium.setStyleSheet("background-color: rgb(255, 197, 66);\n"
"color: rgb(255, 255, 255);\n"
"padding: 0%;\n"
"")
        self.button_medium.setObjectName("button_medium")
        self.verticalLayout_4.addWidget(self.button_medium)
        self.button_hard = QtWidgets.QPushButton(parent=self.widget1)
        self.button_hard.setMinimumSize(QtCore.QSize(300, 50))
        self.button_hard.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.button_hard.setFont(font)
        self.button_hard.setAutoFillBackground(False)
        self.button_hard.setStyleSheet("background-color: rgb(255, 197, 66);\n"
"color: rgb(255, 255, 255);\n"
"padding: 0%;\n"
"")
        self.button_hard.setObjectName("button_hard")
        self.verticalLayout_4.addWidget(self.button_hard)
        self.verticalLayout_2.addWidget(self.widget1, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(mainMenu)
        QtCore.QMetaObject.connectSlotsByName(mainMenu)

    def retranslateUi(self, mainMenu):
        _translate = QtCore.QCoreApplication.translate
        mainMenu.setWindowTitle(_translate("mainMenu", "Speed Sketch"))
        self.button_easy.setText(_translate("mainMenu", "EASY"))
        self.button_medium.setText(_translate("mainMenu", "MEDIUM"))
        self.button_hard.setText(_translate("mainMenu", "HARD"))
