# Form implementation generated from reading ui file 'ui\playScene.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_playScene(object):
    def setupUi(self, playScene):
        playScene.setObjectName("playScene")
        playScene.resize(620, 483)
        icon = QtGui.QIcon.fromTheme("applications-games")
        playScene.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(playScene)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_difficulty = QtWidgets.QLabel(parent=playScene)
        self.label_difficulty.setObjectName("label_difficulty")
        self.verticalLayout_3.addWidget(self.label_difficulty, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_timer = QtWidgets.QLabel(parent=playScene)
        self.label_timer.setObjectName("label_timer")
        self.verticalLayout_3.addWidget(self.label_timer, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_category = QtWidgets.QLabel(parent=playScene)
        self.label_category.setObjectName("label_category")
        self.verticalLayout_3.addWidget(self.label_category, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_phrase = QtWidgets.QLabel(parent=playScene)
        self.label_phrase.setObjectName("label_phrase")
        self.verticalLayout_3.addWidget(self.label_phrase, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_colorselected = QtWidgets.QWidget(parent=playScene)
        self.widget_colorselected.setStyleSheet("background-color:black;")
        self.widget_colorselected.setObjectName("widget_colorselected")
        self.horizontalLayout_2.addWidget(self.widget_colorselected)
        self.choose_color = QtWidgets.QPushButton(parent=playScene)
        self.choose_color.setObjectName("choose_color")
        self.horizontalLayout_2.addWidget(self.choose_color)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.drawing_space = QtWidgets.QVBoxLayout()
        self.drawing_space.setObjectName("drawing_space")
        self.verticalLayout.addLayout(self.drawing_space)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 5)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.setStretch(0, 1)

        self.retranslateUi(playScene)
        QtCore.QMetaObject.connectSlotsByName(playScene)

    def retranslateUi(self, playScene):
        _translate = QtCore.QCoreApplication.translate
        playScene.setWindowTitle(_translate("playScene", "Speed Sketch"))
        self.label_difficulty.setText(_translate("playScene", "Easy"))
        self.label_timer.setText(_translate("playScene", "30 seconds"))
        self.label_category.setText(_translate("playScene", "display category..."))
        self.label_phrase.setText(_translate("playScene", "displaying phrase..."))
        self.choose_color.setText(_translate("playScene", "Pick Color"))
