# Form implementation generated from reading ui file 'ui/resultScene.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import resources_rc.icons_rc
import resources_rc.background_rc


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(791, 810)
        Dialog.setStyleSheet("background: qlineargradient(\n"
"    x1:0, y1:0, x2:1, y2:1,\n"
"    /* Main Background - lighter */\n"
"    stop:0 #1a1c23, \n"
"    \n"
"    /* Top Right Subtle Shadow Slope */\n"
"    stop:0.15 #1a1c23, \n"
"    stop:0.16 #14161c, \n"
"    \n"
"    /* Transition back to main background */\n"
"    stop:0.84 #1a1c23, \n"
"    \n"
"    /* Bottom Right Light Geometric Slice */\n"
"    stop:0.85 #2a2e38, \n"
"    stop:1.0 #2a2e38\n"
");")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(520, 390))
        self.frame_3.setMaximumSize(QtCore.QSize(180, 800))
        self.frame_3.setStyleSheet("background:transparent;\n"
"border:none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_2.setMinimumSize(QtCore.QSize(200, 40))
        self.frame_2.setMaximumSize(QtCore.QSize(200, 40))
        self.frame_2.setStyleSheet("background:transparent; \n"
"border:none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_star1 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_star1.setMinimumSize(QtCore.QSize(30, 30))
        self.label_star1.setMaximumSize(QtCore.QSize(30, 30))
        self.label_star1.setStyleSheet("background:transparent; \n"
"border:none;")
        self.label_star1.setText("")
        self.label_star1.setPixmap(QtGui.QPixmap(":/result/star_rate.svg"))
        self.label_star1.setScaledContents(True)
        self.label_star1.setObjectName("label_star1")
        self.horizontalLayout_2.addWidget(self.label_star1)
        self.label_star2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_star2.setMinimumSize(QtCore.QSize(30, 30))
        self.label_star2.setMaximumSize(QtCore.QSize(30, 30))
        self.label_star2.setStyleSheet("background:transparent; \n"
"border:none;")
        self.label_star2.setText("")
        self.label_star2.setPixmap(QtGui.QPixmap(":/result/star_rate.svg"))
        self.label_star2.setScaledContents(True)
        self.label_star2.setObjectName("label_star2")
        self.horizontalLayout_2.addWidget(self.label_star2)
        self.label_star3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_star3.setMinimumSize(QtCore.QSize(30, 30))
        self.label_star3.setMaximumSize(QtCore.QSize(30, 30))
        self.label_star3.setStyleSheet("background:transparent; \n"
"border:none;")
        self.label_star3.setText("")
        self.label_star3.setPixmap(QtGui.QPixmap(":/result/star_rate.svg"))
        self.label_star3.setScaledContents(True)
        self.label_star3.setObjectName("label_star3")
        self.horizontalLayout_2.addWidget(self.label_star3)
        self.label_star4 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_star4.setMinimumSize(QtCore.QSize(30, 30))
        self.label_star4.setMaximumSize(QtCore.QSize(30, 30))
        self.label_star4.setStyleSheet("background:transparent; \n"
"border:none;")
        self.label_star4.setText("")
        self.label_star4.setPixmap(QtGui.QPixmap(":/result/star_rate.svg"))
        self.label_star4.setScaledContents(True)
        self.label_star4.setObjectName("label_star4")
        self.horizontalLayout_2.addWidget(self.label_star4)
        self.label_star5 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_star5.setMinimumSize(QtCore.QSize(30, 30))
        self.label_star5.setMaximumSize(QtCore.QSize(30, 30))
        self.label_star5.setStyleSheet("background:transparent; \n"
"border:none;")
        self.label_star5.setText("")
        self.label_star5.setPixmap(QtGui.QPixmap(":/result/star_rate.svg"))
        self.label_star5.setScaledContents(True)
        self.label_star5.setObjectName("label_star5")
        self.horizontalLayout_2.addWidget(self.label_star5)
        self.verticalLayout_6.addWidget(self.frame_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_rate = QtWidgets.QLabel(parent=self.frame_3)
        self.label_rate.setMinimumSize(QtCore.QSize(0, 50))
        self.label_rate.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_rate.setStyleSheet("color:white; font-family: \"Arial\", \"Helvetica\", sans-serif;\n"
"border:none;\n"
"font-weight:800;\n"
"font-size:31pt;\n"
"background:transparent; \n"
"border:none;")
        self.label_rate.setObjectName("label_rate")
        self.verticalLayout_6.addWidget(self.label_rate, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label = QtWidgets.QLabel(parent=self.frame_3)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setStyleSheet("color:#C5BABB;\n"
"font-weight:600;")
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.sketch_card = QtWidgets.QWidget(parent=self.frame_3)
        self.sketch_card.setMinimumSize(QtCore.QSize(500, 300))
        self.sketch_card.setStyleSheet("border:2px solid #3F4657;\n"
"border-radius:20px;")
        self.sketch_card.setObjectName("sketch_card")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.sketch_card)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_sketch = QtWidgets.QLabel(parent=self.sketch_card)
        self.label_sketch.setStyleSheet("border:2px solid #3F4657;\n"
"border-radius:20px;")
        self.label_sketch.setObjectName("label_sketch")
        self.horizontalLayout_4.addWidget(self.label_sketch)
        self.verticalLayout_6.addWidget(self.sketch_card, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_3 = QtWidgets.QWidget(parent=self.frame_3)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_3.setStyleSheet("background-color:#1C1B1B;\n"
"border-radius:10px;\n"
"border:1px solid #262627;")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_2.setStyleSheet("color:#C9BFC0;\n"
"font-family: \"Arial\", \"Helvetica\", sans-serif;\n"
"border:none;\n"
"font-weight:600;\n"
"font-size:8pt;\n"
"")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignBottom)
        self.label_timespent = QtWidgets.QLabel(parent=self.widget_3)
        self.label_timespent.setStyleSheet("color:white;\n"
"font-family: \"Arial\", \"Helvetica\", sans-serif;\n"
"border:none;\n"
"font-weight:600;\n"
"font-size:18pt")
        self.label_timespent.setObjectName("label_timespent")
        self.verticalLayout_3.addWidget(self.label_timespent, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_3.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(parent=self.frame_3)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_2.setStyleSheet("background-color:#1C1B1B;\n"
"border-radius:10px;\n"
"border:1px solid #262627;")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.label_4 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_4.setStyleSheet("color:#C9BFC0;\n"
"font-family: \"Arial\", \"Helvetica\", sans-serif;\n"
"border:none;\n"
"font-weight:600;\n"
"font-size:8pt;\n"
"")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_accuracy = QtWidgets.QLabel(parent=self.widget_2)
        self.label_accuracy.setStyleSheet("color:white;\n"
"font-family: \"Arial\", \"Helvetica\", sans-serif;\n"
"border:none;\n"
"font-weight:600;\n"
"font-size:18pt")
        self.label_accuracy.setObjectName("label_accuracy")
        self.verticalLayout_4.addWidget(self.label_accuracy, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.horizontalLayout_3.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(parent=self.frame_3)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget.setStyleSheet("background-color:#1C1B1B;\n"
"border-radius:10px;\n"
"border:0.5px solid #454955;")
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.label_11 = QtWidgets.QLabel(parent=self.widget)
        self.label_11.setStyleSheet("color:#C9BFC0;\n"
"font-family: \"Arial\", \"Helvetica\", sans-serif;\n"
"border:none;\n"
"font-weight:600;\n"
"font-size:8pt;\n"
"")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_perfectstreak = QtWidgets.QLabel(parent=self.widget)
        self.label_perfectstreak.setStyleSheet("color:white;\n"
"font-family: \"Arial\", \"Helvetica\", sans-serif;\n"
"border:none;\n"
"font-weight:600;\n"
"font-size:18pt")
        self.label_perfectstreak.setObjectName("label_perfectstreak")
        self.verticalLayout_5.addWidget(self.label_perfectstreak, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.horizontalLayout_3.addWidget(self.widget)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.button_next = QtWidgets.QPushButton(parent=self.frame_3)
        self.button_next.setMinimumSize(QtCore.QSize(300, 70))
        self.button_next.setMaximumSize(QtCore.QSize(100, 70))
        self.button_next.setStyleSheet("QPushButton{background-color:#E9C400;\n"
" font-weight: bold;\n"
"   border-top-left-radius: 15px;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-left-radius: 8px;\n"
"    border-bottom-right-radius: 15px;\n"
"    color: black;\n"
"    font-family: \"Arial\", \"Helvetica\", sans-serif;\n"
"\n"
"    font-weight: bold;\n"
"    font-style: italic;\n"
"    letter-spacing: -0.025em;\n"
"font-size:16px\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color:#FFD901;\n"
"}\n"
"")
        self.button_next.setObjectName("button_next")
        self.verticalLayout_6.addWidget(self.button_next, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem9)
        self.verticalLayout_6.setStretch(1, 1)
        self.verticalLayout_6.setStretch(2, 1)
        self.verticalLayout_6.setStretch(3, 1)
        self.verticalLayout_6.setStretch(4, 1)
        self.verticalLayout_6.setStretch(6, 1)
        self.verticalLayout_6.setStretch(8, 1)
        self.horizontalLayout.addWidget(self.frame_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_rate.setText(_translate("Dialog", "PERFECT!"))
        self.label.setText(_translate("Dialog", "YOUR SKETCH"))
        self.label_sketch.setText(_translate("Dialog", "TextLabel"))
        self.label_2.setText(_translate("Dialog", "TIME SPENT"))
        self.label_timespent.setText(_translate("Dialog", "30s"))
        self.label_4.setText(_translate("Dialog", "ACCURACY"))
        self.label_accuracy.setText(_translate("Dialog", "96%"))
        self.label_11.setText(_translate("Dialog", "PERFECT STREAK"))
        self.label_perfectstreak.setText(_translate("Dialog", "4"))
        self.button_next.setText(_translate("Dialog", "Next"))
