# Form implementation generated from reading ui file 'ui\startingScene.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_startingScene(object):
    def setupUi(self, startingScene):
        startingScene.setObjectName("startingScene")
        startingScene.resize(1060, 238)
        icon = QtGui.QIcon.fromTheme("applications-games")
        startingScene.setWindowIcon(icon)
        startingScene.setAutoFillBackground(False)
        startingScene.setStyleSheet("background-color: rgb(107, 122, 245);")
        self.verticalLayout = QtWidgets.QVBoxLayout(startingScene)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=startingScene)
        self.frame.setStyleSheet("background-color: rgb(107, 122, 245);")
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_difficulty = QtWidgets.QLabel(parent=self.frame)
        self.label_difficulty.setMinimumSize(QtCore.QSize(500, 70))
        self.label_difficulty.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_difficulty.setFont(font)
        self.label_difficulty.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 0%;\n"
"")
        self.label_difficulty.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_difficulty.setObjectName("label_difficulty")
        self.verticalLayout_3.addWidget(self.label_difficulty, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.listwidget_categories = QtWidgets.QListWidget(parent=startingScene)
        self.listwidget_categories.setMinimumSize(QtCore.QSize(200, 50))
        self.listwidget_categories.setMaximumSize(QtCore.QSize(200, 300))
        self.listwidget_categories.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.listwidget_categories.setAutoFillBackground(True)
        self.listwidget_categories.setStyleSheet("\n"
"\n"
"\n"
"QListWidget {\n"
"         background-color: rgb(255, 197, 66);\n"
"        border: 2px solid #3d3d3d;\n"
"        border-radius: 8px;\n"
"        padding: 5px;\n"
"        color: #ffffff;\n"
"        font-size: 14px;\n"
"    }\n"
"    QListWidget::item {\n"
"        padding: 10px;\n"
"        border-bottom: 1px solid #3d3d3d;\n"
"        border-radius: 4px;\n"
"    }\n"
"    QListWidget::item:hover {\n"
"        background-color: #3d3d3d;\n"
"    }\n"
"QListWidget::item:selected {\n"
"        background-color: #2b2b2b;\n"
"        color: white;\n"
"    }")
        self.listwidget_categories.setObjectName("listwidget_categories")
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.CheckState.Checked)
        self.listwidget_categories.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.CheckState.Checked)
        self.listwidget_categories.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.CheckState.Checked)
        self.listwidget_categories.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.CheckState.Checked)
        self.listwidget_categories.addItem(item)
        self.verticalLayout.addWidget(self.listwidget_categories, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_start = QtWidgets.QPushButton(parent=startingScene)
        self.button_start.setMinimumSize(QtCore.QSize(200, 60))
        self.button_start.setMaximumSize(QtCore.QSize(300, 16777215))
        self.button_start.setObjectName("button_start")
        self.horizontalLayout.addWidget(self.button_start, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(startingScene)
        QtCore.QMetaObject.connectSlotsByName(startingScene)

    def retranslateUi(self, startingScene):
        _translate = QtCore.QCoreApplication.translate
        startingScene.setWindowTitle(_translate("startingScene", "Speed Sketch"))
        self.label_difficulty.setText(_translate("startingScene", "Easy"))
        __sortingEnabled = self.listwidget_categories.isSortingEnabled()
        self.listwidget_categories.setSortingEnabled(False)
        item = self.listwidget_categories.item(0)
        item.setText(_translate("startingScene", "Animals"))
        item = self.listwidget_categories.item(1)
        item.setText(_translate("startingScene", "Flowers"))
        item = self.listwidget_categories.item(2)
        item.setText(_translate("startingScene", "Emoji"))
        item = self.listwidget_categories.item(3)
        item.setText(_translate("startingScene", "Vehicle"))
        self.listwidget_categories.setSortingEnabled(__sortingEnabled)
        self.button_start.setText(_translate("startingScene", "Start"))
